input_smi: "Fc1ccc(c(F)c1)C(O)(Cn2ncnc2)Cn3ncnc3"
API_TOKEN: "1aaaaaaaaaaaaaaa"
dock_executable: "/home/soft/dock38DOCK/ucsfdock/docking/DOCK/dock64"
dockfiles_dir: "/path/to/dockfiles_dir"  # Update this path as needed